### ISSUE TITLE
Minimal command not working

### ISSUE THREAD

**Issue by lmjustic** [MeLikeChoco/YuGiOhBot#1]
On my personal channel I was able to invite the bot and after about 8 hours I attempted to use y!minimal true and it worked fine. However, attempting to use the same command on a different server about an hour after adding the bot caused it to say I was using the command incorrectly. 

The difference between the first bot and the second bot other than time is that one was invited with the Manage Messages options (first one) whereas the other wasn't (second one). 

I was able to kick and invite the first bot and use the command again instantly with no issues. I'm doing further testing to see if I can get the second up and running

**Comment by MeLikeChoco** [comment]
I see the error in console. I also noticed some other weird things with my bot, I'll figure things out. I love my spaghetti code. I should probably recode, lmao.

**Comment by lmjustic** [comment]
lol I really appreciate it. The bot is really handy. Even if it doesn't get fixed we'll make do. Thanks again for making this :)

**Comment by MeLikeChoco** [comment]
Did a recode, should be fine now.
